# Generated by Django 6.0.1 on 2026-01-12 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=70, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=70, verbose_name='last name')),
                ('address_one', models.CharField(blank=True, max_length=128, verbose_name='address')),
                ('address_two', models.CharField(blank=True, max_length=128, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=128, verbose_name='country')),
                ('province', models.CharField(blank=True, max_length=128, verbose_name='province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal_code')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone')),
                ('marketing_consent_one', models.BooleanField(default=False, verbose_name='first marketing_consent')),
                ('marketing_consent_two', models.BooleanField(default=False, verbose_name='second marketing_consent')),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='username')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
